const $=s=>document.querySelector(s);let type='movie',catalog=[];
const defaults={catalogBase:'https://vidrock.ru/list',embedBase:'https://vidrock.ru',directUrl:'',preset:'glass',last:null};
const store={get(){try{return {...defaults,...JSON.parse(localStorage.getItem('glassCinema')||'{}')}}catch{return {...defaults}}},set(p){localStorage.setItem('glassCinema',JSON.stringify({...this.get(),...p}))}};
function safeBase(value){try{const u=new URL(value);if(u.protocol!=='https:')throw Error();return u.href.replace(/\/$/,'')}catch{return ''}}
function normalize(data){const a=Array.isArray(data)?data:(data.results||data.items||data.data||[]);return a.map(x=>({id:x.id||x.tmdb_id||x.tmdb||x.ID,title:x.title||x.name||x.original_title||x.original_name||String(x.id||''),year:(x.release_date||x.first_air_date||x.year||'').toString().slice(0,4)})).filter(x=>x.id&&x.title)}
async function loadCatalog(){const s=store.get(),base=safeBase(s.catalogBase);$('#status').textContent='Loading catalogue…';if(!base){catalog=[];$('#status').textContent='Set a valid HTTPS catalogue URL.';return render()}try{const r=await fetch(`${base}/${type}.json`,{cache:'no-store',credentials:'omit',redirect:'follow'});if(!r.ok)throw Error(`HTTP ${r.status}`);catalog=normalize(await r.json());$('#status').textContent=`${catalog.length.toLocaleString()} ${type==='tv'?'series':'movies'} available`;render()}catch{catalog=[];$('#status').textContent='Catalogue unavailable — enter a numeric ID manually.';render()}}
function render(){const q=$('#search').value.trim().toLowerCase();const list=(q?catalog.filter(x=>String(x.id)===q||x.title.toLowerCase().includes(q)):catalog).slice(0,150);$('#results').replaceChildren();for(const x of list){const b=document.createElement('button');b.className='result';const strong=document.createElement('strong');strong.textContent=x.title;const small=document.createElement('small');small.textContent=`ID ${x.id}${x.year?' · '+x.year:''}`;b.append(strong,small);b.onclick=()=>play(x.id,x.title);$('#results').append(b)}}
async function play(id,title=`ID ${id}`){if(!/^\d+$/.test(String(id)))return;const s=store.get(),embedBase=safeBase(s.embedBase),direct=s.directUrl?safeBase(s.directUrl):'';const season=Math.max(1,+$('#season').value||1),episode=Math.max(1,+$('#episode').value||1);$('#empty').hidden=true;$('#playerWrap').hidden=false;$('#nowPlaying').textContent=title+(type==='tv'?` · S${season} E${episode}`:'');if(direct){$('#embed').hidden=true;$('#embed').removeAttribute('src');$('#direct').hidden=false;$('#direct').src=direct;$('#direct').play().catch(()=>{})}else if(embedBase){$('#direct').pause();$('#direct').removeAttribute('src');$('#direct').hidden=true;$('#embed').hidden=false;$('#embed').src=type==='movie'?`${embedBase}/movie/${encodeURIComponent(id)}`:`${embedBase}/tv/${encodeURIComponent(id)}/${season}/${episode}`}store.set({last:{id,title,type,season,episode}})}
function applyPreset(){const w=$('#playerWrap');w.className='player-wrap';if($('#preset').value!=='original')w.classList.add('preset-'+$('#preset').value);store.set({preset:$('#preset').value})}
$('.tabs').addEventListener('click',e=>{if(!e.target.dataset.type)return;type=e.target.dataset.type;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b===e.target));loadCatalog()});
$('#search').oninput=render;$('#loadBtn').onclick=()=>{const q=$('#search').value.trim();const exact=catalog.find(x=>String(x.id)===q)||catalog.find(x=>x.title.toLowerCase()===q.toLowerCase());if(exact)play(exact.id,exact.title);else if(/^\d+$/.test(q))play(q)};$('#search').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loadBtn').click()});
$('#preset').onchange=applyPreset;$('#fullscreen').onclick=async()=>{const el=$('#playerWrap');try{if(el.requestFullscreen)await el.requestFullscreen();else if($('#direct').webkitEnterFullscreen&&!$('#direct').hidden)$('#direct').webkitEnterFullscreen()}catch{}};
function openSettings(){const s=store.get();$('#catalogBase').value=s.catalogBase;$('#embedBase').value=s.embedBase;$('#directUrl').value=s.directUrl||'';$('#settings').hidden=false}$('#settingsBtn').onclick=openSettings;$('#cancelSettings').onclick=()=>$('#settings').hidden=true;$('#settingsForm').onsubmit=e=>{e.preventDefault();const catalogBase=safeBase($('#catalogBase').value),embedBase=safeBase($('#embedBase').value),directUrl=$('#directUrl').value.trim()?safeBase($('#directUrl').value):'';if(!catalogBase||!embedBase)return alert('Catalogue and embed addresses must be valid HTTPS URLs.');store.set({catalogBase,embedBase,directUrl});$('#settings').hidden=true;loadCatalog()};
$('#installBtn').onclick=()=>alert('Open this HTTPS page in Safari, tap Share, then choose Add to Home Screen. A ZIP opened from Files cannot be installed as a web app.');
(async()=>{const s=store.get();$('#preset').value=s.preset;applyPreset();if(window.matchMedia('(display-mode: standalone)').matches)$('#installBtn').hidden=true;await loadCatalog();if(s.last){type=s.last.type||'movie';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#season').value=s.last.season||1;$('#episode').value=s.last.episode||1}if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{})})();